from typing import TypedDict, Optional, Annotated
from dataclasses import dataclass, field
import operator


@dataclass
class Chunk:
    content: str  # The actual code/text snippet extracted from the repository
    file_path: str  # Relative file path (e.g., "src/auth/login.py")
    start_line: int  # Line number where this chunk starts in the file
    end_line: int  # Line number where this chunk ends in the file
    language: str  # Programming language of the file (e.g., "python", "js")
    symbol_name: str  # Name of the function/class this chunk belongs to
    repo_url: str  # GitHub repository URL this chunk is associated with
    score: float = 0.0  # Similarity score from retrieval (used for ranking relevance)


class AgentState(TypedDict):
    repo_url: str  # GitHub repository link provided by the user
    query: str  # User's question about the repository
    messages: Annotated[
        list, operator.add
    ]  # Chat history for maintaining conversation context
    retrieved_chunks: Annotated[
        list, operator.add
    ]  # Relevant chunks retrieved from the vector database
    iteration_count: int  # Number of reasoning/refinement loops executed by the agent
    final_answer: str  # Final response generated by the LLM
    cited_files: list  # List of file paths (with optional line ranges) used in answer
    error: Optional[str]  # Error message if something fails, otherwise None
